import express, { Router } from 'express';
import { authMiddleware } from '../middlewares/authMiddleware';
import { userRouter } from './user/userRouter';
import { teacherRouter } from './teacher/teacherRouter';
import { levelRouter } from './level/levelRouter';
import { timeRouter } from './time/timeRouter';
import { dayRouter } from './day/dayRouter';
import { bankAccountRouter } from './bank-account/bankAccountRouter';
import { transactionTypeRouter } from './transaction-type/transactionTypeRouter';
import { studentStatusRouter } from './student-status/studentStatusRouter';
import { transactionStatusRouter } from './transaction-status/transactionStatusRouter';
import { classPriceRouter } from './class-price/classPriceRouter';
import { batchRouter } from './batch/batchRouter';
import { classRouter } from './class/classRouter';
import { scheduleRouter } from './schedule/scheduleRouter';
import { moduleRouter } from './module/moduleRouter';
import { componentRouter } from './component/componentRouter';
import { taskRouter } from './task/taskRouter';
import { scoreRouter } from './score/scoreRouter';
import { attendanceRouter } from './attendance/attendanceRouter';
import { billRouter } from './bill/billRouter';
import { transactionRouter } from './transaction/transactionRouter';
import { enrollmentRouter } from './enrollment/enrollmentRouter';
import { studentRouter } from './student/studentRouter';
import { adminRouter } from './admin/adminRouter';

export const router: Router = express.Router();
router.use(authMiddleware);
router.use(userRouter);
router.use(teacherRouter);
router.use(levelRouter);
router.use(timeRouter);
router.use(dayRouter);
router.use(bankAccountRouter);
router.use(transactionTypeRouter);
router.use(studentStatusRouter);
router.use(transactionStatusRouter);
router.use(classPriceRouter);
router.use(batchRouter);
router.use(classRouter);
router.use(scheduleRouter);
router.use(moduleRouter);
router.use(componentRouter);
router.use(taskRouter);
router.use(scoreRouter);
router.use(attendanceRouter);
router.use(billRouter);
router.use(transactionRouter);
router.use(enrollmentRouter);
router.use(studentRouter);
router.use(adminRouter);
