import express, { Router } from 'express';
import { userRouter } from './user/userRouter';
import { teacherRouter } from './teacher/teacherRouter';
import { levelRouter } from './level/levelRouter';
import { timeRouter } from './time/timeRouter';
import { dayRouter } from './day/dayRouter';
import { bankAccountRouter } from './bank-account/bankAccountRouter';
import { transactionTypeRouter } from './transaction-type/transactionTypeRouter';
// import { studentStatusRouter } from './student-status/studentStatusRouter';
import { transactionStatusRouter } from './transaction-status/transactionStatusRouter';
import { classPriceRouter } from './class-price/classPriceRouter';
import { batchRouter } from './batch/batchRouter';
import { classRouter } from './class/classRouter';
import { scheduleRouter } from './schedule/scheduleRouter';
import { moduleRouter } from './module/moduleRouter';
import { componentRouter } from './component/componentRouter';
import { taskRouter } from './task/taskRouter';
import { scoreRouter } from './score/scoreRouter';
import { attendanceRouter } from './attendance/attendanceRouter';
import { billRouter } from './bill/billRouter';
import { transactionRouter } from './transaction/transactionRouter';
import { studentRouter } from './student/studentRouter';
import { adminRouter } from './admin/adminRouter';
import { enrollmentRouter } from './enrollment/enrollmentRouter';
import { announcementRouter } from './announcement/announcementRouter';
import { eventRouter } from './event/eventRouter';
import { academicPeriodRouter } from './academicPeriod/academicPeriodRouter';
import { academicCalendarRouter } from './academicCalendar/academicCalendarRouter';
import { paymentFeeRouter } from './paymentFee/paymentFeeRouter';
import { classScheduleRouter } from './classSchedule/classScheduleRouter';

export const superRouter: Router = express.Router();
superRouter.use(userRouter);
superRouter.use(teacherRouter);
superRouter.use(levelRouter);
superRouter.use(timeRouter);
superRouter.use(dayRouter);
superRouter.use(bankAccountRouter);
superRouter.use(transactionTypeRouter);
// superRouter.use(studentStatusRouter);
superRouter.use(transactionStatusRouter);
superRouter.use(classPriceRouter);
superRouter.use(batchRouter);
superRouter.use(classRouter);
superRouter.use(scheduleRouter);
superRouter.use(moduleRouter);
superRouter.use(componentRouter);
superRouter.use(taskRouter);
superRouter.use(scoreRouter);
superRouter.use(attendanceRouter);
superRouter.use(billRouter);
superRouter.use(transactionRouter);
superRouter.use(enrollmentRouter);
superRouter.use(studentRouter);
superRouter.use(adminRouter);
superRouter.use(announcementRouter);
superRouter.use(eventRouter);
superRouter.use(academicPeriodRouter);
superRouter.use(academicCalendarRouter);
superRouter.use(paymentFeeRouter);
superRouter.use(classScheduleRouter);
